export const TRIP_SPOTIFY_CONFIG_REQUESTED = 'TRIP_SPOTIFY_CONFIG_REQUESTED'
export const TRIP_SPOTIFY_CONFIG_RESOLVED  = 'TRIP_SPOTIFY_CONFIG_RESOLVED'
export const TRIP_SPOTIFY_AUTHENTICATED    = 'TRIP_SPOTIFY_AUTHENTICATED'

export const TRIP_SPOTIFY_ARTISTS_REQUESTED = 'TRIP_SPOTIFY_ARTISTS_REQUESTED'
export const TRIP_SPOTIFY_ARTISTS_RESOLVED  = 'TRIP_SPOTIFY_ARTISTS_RESOLVED'
export const TRIP_SPOTIFY_ARTISTS_SELECT    = 'TRIP_SPOTIFY_ARTISTS_SELECT'
export const TRIP_SPOTIFY_ARTISTS_UNSELECT  = 'TRIP_SPOTIFY_ARTISTS_UNSELECT'
export const TRIP_SPOTIFY_ARTISTS_DONE      = 'TRIP_SPOTIFY_ARTISTS_DONE'

export const TRIP_LOADED                    = 'TRIP_LOADED'
