// 
export const TRIP_SPOTIFY_CONFIG_REQUESTED = 'TRIP_SPOTIFY_CONFIG_REQUESTED'
export const TRIP_SPOTIFY_CONFIG_RESOLVED  = 'TRIP_SPOTIFY_CONFIG_RESOLVED'
export const TRIP_SPOTIFY_AUTHENTICATED    = 'TRIP_SPOTIFY_AUTHENTICATED'

